Added -f (--force) option to install bundler
```
ERROR:  Error installing bundler:
	"bundle" from bundler conflicts with /opt/rbenv/versions/2.6.3/bin/bundle
```